@max_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE5NjY5Njl9.Gj7dNhnCBKMfqWQ4cHJMpHp5DM5__rwSQYXo2mRzlR8
@test_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE5NjY5MTF9.JRmbWHFzpsAkMP_vkgybh7gIuw2hVS5pqqWxdeIlsd0
@corpse_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjE5NjY4NDJ9.W7jeBo3-7XWqQb6pS25Bf5BZuAALTJK3hK2R0o-tWfs


#user.update(admin: !user.admin) | user.admin flips admin and shows status

### Product Index (everyone)
get http://localhost:3000/products.json


### Product Show (everyone)
get http://localhost:3000/products/1.json

### Product Create (admin) Tested
post http://localhost:3000/products
Authorization: Bearer {{max_jwt}}
Content-Type: application/json

{
  "name": "Corn!!",
  "description": "A yellow vegetable",
  "price": 40,
  "supplier_id": 2
}

### Product Update (admin) Tested
patch http://localhost:3000/products/8
Authorization: Bearer {{max_jwt}}
Content-Type: application/json

{
  "name": "Red Pepper"
}

### Product Delete (admin) TEST TEST TEST
DELETE http://localhost:3000/products/
Authorization: Bearer {{max_jwt}}


#################################################
# Supplier Test Calls
#################################################

### Supplier Index (everyone)
get http://localhost:3000/suppliers

#################################################
#Creating new url
#################################################

### Images Create (Admin)
post http://localhost:3000/images
Authorization: Bearer {{max_jwt}}
Content-Type: application/json

{
  "url": "testing",
  "product_id": "19"
}

#################################################
#decomp
# Currently image_url is 1 spaces inside Products
#   Remove images from Products
#   Create Image model (for belongs_to :Products), should have url && product_id
#################################################

### User Signup (Users#Create) (everyone)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "corpse@dead.com",
  "password": "password",
  "password_confirmation": "password"
}

### Login/Sessions Create (everyone)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "max@email.com",
  "password": "password"
}


### Order Create (user) TESTED
post http://localhost:3000/orders.json
Authorization: Bearer {{max_jwt}}
Content-Type: application/json

{

}

### Orders Index (User) Tested
get http://localhost:3000/orders.json
Authorization: Bearer {{max_jwt}}

### Orders Show (User) Tested
get http://localhost:3000/orders/2
Authorization: Bearer {{max_jwt}}

#################################################
#Creating new carted_products for orders
#################################################

#1 Remove quantity and product_id from Order table (1b) xx
#2 create carted_products table containing: (1a) xx
  #3 user_id integer
  #4 product_id integer
  #5 quantity integer
  #6 order_id integer
  #7 status string
#8 Need to create 4 paths for carted_products (3) xx
  #9 Index
  #10 Create
  #10 Update (Don't worry about it for demo)
  #11 Destroy (check status for 'removed')
#12 refer tables with has_many and belongs_to (hint, if it has ID, it belongs to said ID) (hint_2: belongs_to :order, optional: true)  (2)  xx
#13
  #Update Order routes to use the Carted_Products table
    #loop through carted_products table finding all matching user_id + status == carted ! removed/purchased
    #Def find all carted products
    #calculate math stuff
    #modify carted to purchased 

### Carted_Product Index (Eventualy tie to user only)
get http://localhost:3000/carted_products 
Authorization: Bearer {{max_jwt}}

### Carted_Product Create 
post http://localhost:3000/carted_products.json
Authorization: Bearer {{max_jwt}}
Content-Type: application/json

{
"product_id": 1,
"quantity": 2
}

### Carted_Product Destroy (Status to removed)
DELETE http://localhost:3000/carted_products/1.json
Authorization: Bearer {{max_jwt}}