
get http://localhost:3000/products.json

### 
get http://localhost:3000/products/1.json

###
post http://localhost:3000/products
Content-Type: application/json

{
  "name": "Testing",
  "description": "A red fruit",
  "price": 4,
  "supplier_id": 2
}

###
patch http://localhost:3000/products/6
Content-Type: application/json

{
  "name": "Yellow Pepper"
}

###
DELETE http://localhost:3000/products/13

# Supplier Test Calls

###

get http://localhost:3000/suppliers

#Creating new url

###
post http://localhost:3000/images
Content-Type: application/json

{
  "url": "https://post.greatist.com/wp-content/uploads/sites/2/2021/10/GRT-bananas-spiral-circle-1200x628-facebook-1200x628.jpg",
  "product_id": "1"
}

#decomp
# Currently image_url is 1 spaces inside Products
#   Remove images from Products
#   Create Image model (for belongs_to :Products), should have url && product_id

### User Signup (Users#Create)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Login/Sessions Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}