
get http://localhost:3000/products.json

### 
get http://localhost:3000/products/1.json

###
post http://localhost:3000/products
Content-Type: application/json

{
  "name": "Testing",
  "description": "A red fruit",
  "price": 4,
  "image_url": "google.com",
  "supplier_id": 2
}

###
patch http://localhost:3000/products/6
Content-Type: application/json

{
  "name": "Yellow Pepper"
}

###
DELETE http://localhost:3000/products/13

# Supplier Test Calls

###

get http://localhost:3000/suppliers


#decomp
Currently image_url is 1 spaces inside Products
  Remove images from Products
  Create Image model (for belongs_to :Products), should have url && product_id
  