
get http://localhost:3000/products


### 
get http://localhost:3000/products/1

###
post http://localhost:3000/products
Content-Type: application/json

{
  "title": "Strawberry",
  "description": "A red fruit",
  "price": 4,
  "image_url": "google.com"
}

###
patch http://localhost:3000/products/5
Content-Type: application/json

{
  "title": "Lettuce",
  "description": "A green leafy vegetable",
  "price": 2,
  "image_url": "google.com"
}