
get http://localhost:3000/products.json

### 
get http://localhost:3000/products/1.json

###
post http://localhost:3000/products
Content-Type: application/json

{
  "title": "Egg",
  "description": "A red fruit",
  "price": 4,
  "image_url": "google.com"
}

###
patch http://localhost:3000/products/6
Content-Type: application/json

{
  "title": "Yellow Pepper"
}

###
DELETE http://localhost:3000/products/13